name: GitHub Pages
on:
  push:
    branches: v3.6
jobs:
  Approve :
    runs-on: ubuntu-latest
    environment: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
  build:
   runs-on: ubuntu-latest
   needs: Approve
   steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: |
           npm install -g @angular/cli
           mkdir user
           cd user
           ls -la
           npm i
           npm run build:prod
           ls -la
    - name: listings
      run: |
           ls -la
           cd dist
           ls -la
    - name: zippings
      uses: papeloto/action-zip@v1
      with:
          files: dist/user
          dest: user.zip
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: user
        path: user.zip
                     
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          SOURCE: "user.zip"
          REMOTE_HOST: ${{ secrets.HOSTDNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.USER_DIR }}
          script: sh ui-builds-unzip.sh 
